---
- name: Установка Apache
  hosts: [test]
  become: yes
  tasks:
    - name: Установить httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Запустить и включить сервис
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
